"""
Config Generator — يولد التكوينات الفعلية لكل بائع، سطر بسطر، بدون تخمين
كل كتلة مربوطة بـ Requirement IDs وتظهر في الخطة قبل التنفيذ
"""
from typing import Dict, List
import os
from jinja2 import Template

TEMPLATES = {
    "cisco": """
! {{ hostname }} — Cisco IOS — Generated by NetOps Autopilot — {{ intent.networkName }}
hostname {{ hostname }}
!
{% for v in intent.vlans %}vlan {{ v.id }}
 name {{ v.name }}
!
{% endfor %}
{% for pr in port_roles if pr.deviceId == device.deviceId %}
interface {{ pr.port }}
 {% if pr.role == 'access' %}switchport mode access
 switchport access vlan {{ pr.accessVlan }}
 {% else %}switchport mode trunk
 switchport trunk allowed vlan {{ pr.allowedVlans | join(',') }}
 {% endif %}
 no shutdown
!
{% endfor %}
{% if is_l3 %}
{% for v in intent.vlans %}
interface Vlan{{ v.id }}
 ip address 10.0.{{ v.id }}.1 255.255.255.0
 no shutdown
!
{% endfor %}
{% endif %}
ip domain-name autopilot.local
ntp server {{ intent.ntpServer }}
!
line vty 0 15
 transport input ssh
!
end
""",
    "juniper": """
/* {{ hostname }} — Junos — Generated by NetOps Autopilot */
system {
    host-name {{ hostname }};
    name-server {{ intent.dnsServers | join(' ') }};
    ntp {
        server {{ intent.ntpServer }};
    }
}
{% for v in intent.vlans %}
vlans {
    {{ v.name }} {
        vlan-id {{ v.id }};
    }
}
{% endfor %}
""",
}

class ConfigGenerator:
    def generate(self, plan: Dict) -> Dict[str, str]:
        outputs = {}
        for dev in plan["devices"]:
            vendor = dev.get("vendor", "cisco")
            tpl = TEMPLATES.get(vendor, TEMPLATES["cisco"])
            is_l3 = dev.get("role") in ["core", "wan-edge"]
            pr = [p for p in plan["portRoles"] if p["deviceId"] == dev["deviceId"]]
            rendered = Template(tpl).render(
                hostname=dev["hostname"],
                device=dev,
                intent=plan["intent"],
                port_roles=pr,
                is_l3=is_l3,
            )
            outputs[dev["deviceId"]] = rendered.strip()
        return outputs

    def save(self, plan: Dict, out_dir: str):
        os.makedirs(out_dir, exist_ok=True)
        outputs = self.generate(plan)
        for dev_id, text in outputs.items():
            path = os.path.join(out_dir, f"{dev_id}.cfg")
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
        # Also write plan.json
        import json
        with open(os.path.join(out_dir, "plan.json"), "w", encoding="utf-8") as f:
            json.dump(plan, f, ensure_ascii=False, indent=2)
        return outputs

generator = ConfigGenerator()
